### ISSUE TITLE
Create a new logo

### ISSUE THREAD

**Issue by 0x61nas** [anas-elgarhy/cmus-rpc-rs#11]

**Comment by ashiskumarnaik** [comment]
Hi @anas-elgarhy can you point me to your old logo.

**Comment by 0x61nas** [comment]
It's in the `assets/cover` directory
![image](https://raw.githubusercontent.com/anas-elgarhy/cmus-rpc-rs/master/assets/cover/cmus.jpg)

**Comment by ashiskumarnaik** [comment]
assign me I want to create the new logo.

**Comment by 0x61nas** [comment]
Well sure, and thanks in advance 💙
