### ISSUE TITLE
Create a basic unit-tests

### ISSUE THREAD

**Issue by 0x61nas** [anas-elgarhy/cmus-rpc-rs#9]

**Comment by ashiskumarnaik** [comment]
Hi @anas-elgarhy , any details on this , what to do ?

**Comment by ashiskumarnaik** [comment]
@anas-elgarhy on which part the unit test will be performed?

**Comment by 0x61nas** [comment]
hmmmmmmmmmmmmmmmmmmmmmmm

**Comment by 0x61nas** [comment]
Honestly, I have no idea 🙂😂 because I didn't take tests into account when designing unfortunately, but I think the `config` module and the `debug `module would be a good and easy place to write unit tests for them
